# Generated by Django 4.1.4 on 2022-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_items_slug_alter_items_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='This is the description of the product'),
            preserve_default=False,
        ),
    ]
