# Generated by Django 4.1.3 on 2022-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('NP', 'Not Processed'), ('P', 'Processing'), ('OD', 'Out for Delivery'), ('D', 'Delivered')], default='NP', max_length=2),
            preserve_default=False,
        ),
    ]
