# Generated by Django 4.1.3 on 2022-12-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
        ('core', '0005_remove_items_status_orderitems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.AddField(
            model_name='items',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playground.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.customer'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.customer'),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.customer'),
        ),
    ]
