# Generated by Django 4.1.4 on 2022-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_items_quantity_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_slug',
            field=models.SlugField(default='order-1'),
            preserve_default=False,
        ),
    ]
