# Generated by Django 4.1.4 on 2022-12-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_slug',
        ),
    ]
