# Generated by Django 4.1.3 on 2022-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_items_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='seller',
            new_name='seller_id',
        ),
        migrations.RemoveField(
            model_name='sellerorders',
            name='seller',
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='seller_id',
            field=models.IntegerField(default=-1),
        ),
    ]
