# Generated by Django 4.1.3 on 2022-12-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_seller_items_seller_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorders',
            name='products',
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='customer_address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='customer_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='customer_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.items'),
        ),
    ]
